### ISSUE TITLE
Add Roadmap

### ISSUE THREAD

**Issue by hiway** [zentropi/python-zentropi#21]
- [ ] Add roadmap to documentation
- [ ] Link from README
- [ ] Verify it is published and linked from README
